# Generated by Django 6.0 on 2026-01-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_institution_rename_degree_education_degree_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='institution_link',
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='educations', to='resume.institution'),
        ),
    ]
