# Generated by Django 6.0 on 2026-01-06 04:41

from django.db import migrations

def backfill_orgs(apps, schema_editor):
    Experience = apps.get_model('resume', 'Experience')
    Organization = apps.get_model('resume', 'Organization')

    # Build a cache of orgs we've created (avoid duplicates)
    cache = {}

    # Pull distinct organization names from the old text field
    names = (
        Experience.objects
        .values_list('organization', flat=True)
        .distinct()
    )

    for name in names:
        # Normalize; handle blanks gracefully
        long_name = (name or '').strip() or 'Unknown Organization'
        short_name = long_name[:100]
        org = cache.get(long_name)
        if not org:
            org, _ = Organization.objects.get_or_create(
                long_name=long_name,
                defaults={'short_name': short_name}
            )
            cache[long_name] = org

    # Now assign FK for each experience
    for exp in Experience.objects.filter(organization_fk__isnull=True):
        ln = (exp.organization or '').strip() or 'Unknown Organization'
        org = cache.get(ln)
        if org:
            exp.organization_fk_id = org.id
            exp.save(update_fields=['organization_fk'])

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('resume', '0004_organization_experience_organization_fk'),  # replace with the migration that added Organization + FK
    ]
    operations = [
        migrations.RunPython(backfill_orgs, reverse_code=noop),
    ]
