# Generated by Django 6.0 on 2026-01-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_backfill_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='organization',
        ),        
        migrations.RenameField(
                    model_name='experience',
                    old_name='organization_fk',
                    new_name='organization',
                ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='resume.organization'),
        ),
    ]
