# Generated by Django 6.0 on 2026-01-06 21:14

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def backfill_target(apps, schema_editor):
    Experience = apps.get_model('resume', 'Experience')
    Organization = apps.get_model('resume', 'Organization')
    # If you already allow experiences at universities, you can also backfill Institution
    Institution = apps.get_model('resume', 'Institution')

    org_ct = ContentType.objects.get_for_model(Organization)
    inst_ct = ContentType.objects.get_for_model(Institution)

    for exp in Experience.objects.all():
        # Primary case: existing org FK -> point target at Organization
        if getattr(exp, 'organization_id', None):
            exp.target_content_type_id = org_ct.id
            exp.target_object_id = exp.organization_id
            exp.save(update_fields=['target_content_type_id', 'target_object_id'])
        # Optional secondary case: if you later add institution FK on Experience
        elif getattr(exp, 'institution_id', None):
            exp.target_content_type_id = inst_ct.id
            exp.target_object_id = exp.institution_id
            exp.save(update_fields=['target_content_type_id', 'target_object_id'])
        # else: leave null for now; you can set target manually in admin later

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('resume', '0007_experience_target_content_type_and_more'),  # replace with the migration that added the fields
    ]
    operations = [
        migrations.RunPython(backfill_target, reverse_code=noop)
    ]
