# Generated by Django 6.0 on 2026-01-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resume', '0008_backfill_experience_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='target_object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
