# Generated by Django 6.0 on 2026-01-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resume', '0010_leadership_leadershiphighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('preprint', 'Preprint'), ('thesis', 'Thesis'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('poster', 'Poster'), ('other', 'Other')], default='journal', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('journal_or_venue', models.CharField(blank=True, max_length=200)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='publications', to='resume.skill')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('corresponding', models.BooleanField(default=False)),
                ('me', models.BooleanField(default=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='resume.publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
