# Generated by Django 6.0 on 2026-01-09 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_publication_publicationauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResumePresetExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.experience')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_experiences', to='resume.resumepreset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('preset', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='ResumePresetLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.leadership')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_leadership', to='resume.resumepreset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('preset', 'leadership')},
            },
        ),
        migrations.CreateModel(
            name='ResumePresetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_projects', to='resume.resumepreset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.project')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('preset', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ResumePresetPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_publications', to='resume.resumepreset')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.publication')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('preset', 'publication')},
            },
        ),
    ]
