# Generated by Django 6.0 on 2026-01-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_resumepreset_resumepresetexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePresetEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.education')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_educations', to='resume.resumepreset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('preset', 'education')},
            },
        ),
    ]
