# Generated by Django 6.0 on 2026-01-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_resumepreseteducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('print', 'Print (PDF)'), ('preview', 'Preview (browser)')], max_length=20)),
                ('file', models.FileField(upload_to='templates/resume/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resumepreset',
            name='preview_template_file',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'preview'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets_preview', to='resume.templatefile'),
        ),
        migrations.AddField(
            model_name='resumepreset',
            name='print_template_file',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'print'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets_print', to='resume.templatefile'),
        ),
    ]
