# Generated by Django 6.0 on 2026-01-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_templatefile_resumepreset_preview_template_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='organization',
        ),
    ]
